services:
  db_formulario_contacto:
    container_name: formulario_contacto
    image: mysql:8.0

    volumes:
      - mysql_uade_db:/var/lib/mysql

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    restart: unless-stopped

    networks:
      - uade-network
  
  api:
    container_name: api-formulario_contacto
    
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    
    ports:
      - "8000:8000"

    env_file:
      - ./Backend/.env

    volumes:
      - ./Backend:/app
      - ./Backend/logs:/app/logs
    
    depends_on:
      - db_formulario_contacto
    
    networks:
      - uade-network

    command: ["production"]

volumes:
  mysql_uade_db:

networks:
  uade-network:
    driver: bridge
